<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ICounter\Task11.Counter.csproj" />
    <ProjectReference Include="..\Task1\Task11.Monitor\Task11.Monitor.csproj" />
    <ProjectReference Include="..\Task1\Task11.Mutex\Task11.Mutex.csproj" />
    <ProjectReference Include="..\Task1\Task11.Semaphore\Task11.Semaphore.csproj" />
  </ItemGroup>

</Project>
